# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-20 03:22
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='姓名', max_length=32)),
                ('job_id', models.CharField(help_text='工号', max_length=32)),
                ('user', models.OneToOneField(help_text='登录账号', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AnswerQuestionnaire',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(help_text='公司名', max_length=128)),
                ('address', models.CharField(help_text='公司地址', max_length=128)),
                ('phone', models.CharField(help_text='座机', max_length=32)),
                ('industry', models.CharField(help_text='行业', max_length=16)),
                ('web_site', models.CharField(help_text='网址', max_length=128)),
                ('uscc', models.CharField(help_text='统一社会信用代码', max_length=128)),
                ('create_date', models.DateField(help_text='创建时间')),
                ('regist_amount', models.IntegerField(help_text='注册资金')),
                ('corporation', models.CharField(help_text='法人', max_length=128)),
                ('wechat', models.CharField(help_text='微信公众账号', max_length=128)),
                ('email', models.CharField(help_text='邮箱', max_length=128)),
                ('employee_numbers', models.IntegerField(help_text='企业人数')),
                ('business_nature', models.CharField(help_text='企业性质', max_length=128)),
                ('business_scope', models.TextField(help_text='经营范围')),
                ('description', models.TextField(help_text='公司简介')),
                ('stock_code', models.CharField(default='', help_text='股票代码', max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(help_text='文件名', max_length=128)),
                ('savename', models.CharField(help_text='保存时的文件名', max_length=128)),
                ('size', models.IntegerField(help_text='文件大小')),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(help_text='选项内容', max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='JoinQuestionnaire',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateField(help_text='参与时间')),
                ('is_done', models.BooleanField(help_text='是否完成该问卷')),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='题目', max_length=128)),
                ('is_checkbox', models.BooleanField(help_text='是否多选')),
            ],
        ),
        migrations.CreateModel(
            name='Questionnaire',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='标题', max_length=128)),
                ('create_date', models.DateField(help_text='创建时间')),
                ('expire_date', models.DateField(help_text='截止时间')),
                ('quantity', models.IntegerField(help_text='问卷总数')),
                ('left', models.IntegerField(help_text='剩余问卷数量')),
                ('state', models.IntegerField(default=0, help_text='0-->草稿状态,1-->待审核状态,2-->审核失败,3-->审核通过,4-->已发布')),
                ('customer', models.ForeignKey(help_text='问卷所属客户', on_delete=django.db.models.deletion.CASCADE, to='Question.Customer')),
            ],
        ),
        migrations.CreateModel(
            name='QuestionnaireComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateField(auto_now=True, help_text='审核时间')),
                ('comment', models.TextField(help_text='审核内容')),
                ('admin', models.ForeignKey(help_text='审核人', on_delete=django.db.models.deletion.CASCADE, to='Question.Admin')),
                ('questionnaire', models.ForeignKey(help_text='审核的问卷', on_delete=django.db.models.deletion.CASCADE, to='Question.Questionnaire')),
            ],
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='姓名', max_length=32)),
                ('gender', models.CharField(help_text='性别', max_length=32)),
                ('birthday', models.DateField(help_text='出生日期')),
                ('marital_status', models.CharField(help_text='婚姻状况', max_length=32)),
                ('mobile', models.CharField(help_text='手机号码', max_length=32)),
                ('qq', models.CharField(help_text='QQ', max_length=32)),
                ('wechat', models.CharField(help_text='微信', max_length=128)),
                ('job', models.CharField(help_text='工作', max_length=128)),
                ('address', models.CharField(help_text='地址', max_length=128)),
                ('email', models.CharField(help_text='邮箱', max_length=128)),
                ('education', models.CharField(help_text='学历', max_length=128)),
                ('major', models.CharField(help_text='专业', max_length=128)),
                ('photo', models.OneToOneField(help_text='头像', on_delete=django.db.models.deletion.CASCADE, to='Question.Image')),
                ('user', models.OneToOneField(help_text='系统登录用户', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='question',
            name='questionnaire',
            field=models.ForeignKey(help_text='问题所属的问卷', on_delete=django.db.models.deletion.CASCADE, to='Question.Questionnaire'),
        ),
        migrations.AddField(
            model_name='joinquestionnaire',
            name='questionnaire',
            field=models.ForeignKey(help_text='参与的问卷', on_delete=django.db.models.deletion.CASCADE, to='Question.Questionnaire'),
        ),
        migrations.AddField(
            model_name='joinquestionnaire',
            name='userinfo',
            field=models.ForeignKey(help_text='用户', on_delete=django.db.models.deletion.CASCADE, to='Question.UserInfo'),
        ),
        migrations.AddField(
            model_name='item',
            name='question',
            field=models.ForeignKey(help_text='题目', on_delete=django.db.models.deletion.CASCADE, to='Question.Question'),
        ),
        migrations.AddField(
            model_name='customer',
            name='logo',
            field=models.OneToOneField(help_text='logo', on_delete=django.db.models.deletion.CASCADE, to='Question.Image'),
        ),
        migrations.AddField(
            model_name='customer',
            name='user',
            field=models.OneToOneField(help_text='系统登录用户', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='answerquestionnaire',
            name='item',
            field=models.ForeignKey(help_text='选项', on_delete=django.db.models.deletion.CASCADE, to='Question.Item'),
        ),
        migrations.AddField(
            model_name='answerquestionnaire',
            name='userinfo',
            field=models.ForeignKey(help_text='用户', on_delete=django.db.models.deletion.CASCADE, to='Question.UserInfo'),
        ),
    ]
